### ISSUE TITLE
Collect Survey Import

### ISSUE THREAD

**Issue by minotogna** [openforis/arena#710]
- [x] Allow import of .collect file (see #696)
- [x] Import survey description (see #699)
- [ ] Import ApplyIf and Messages (see #705)
- [ ] Import DisplayAs for code attribute (see #736)
- [ ] CollectReportView: add column ```SEVERITY``` (ERROR | WARNING) after ```Type``` (see #704)
- [ ] When collect attribute has a unit specified, add to arena label the unit between square brackets. e.g. Dbh [cm]
